name: CI on Pull Requests

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - LICENSE
      - '*.md'
      - .github/media/**

# Allow one concurrent deployment
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: false

jobs:
  syntax-tests:
    name: Syntax tests (${{ matrix.build }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      package_name: Tact
    strategy:
      matrix:
        include:
          - build: 4169  # default is 'latest'
          - build: 3210  # latest version of ST3 with a test binary
    steps:
      - uses: actions/checkout@v3

      - uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          package_name: ${{ env.package_name }}
          package_root: ${{ env.package_name }}
